SELECT DISTINCT ?uri ?name ?description ?thumbnail ?style ?manufacturer ?layout WHERE {
    ?uri a dbo:Automobile;

    rdfs:label ?name;
    dbo:abstract ?description;
    dbo:thumbnail ?thumbnail;

    dbo:bodyStyle ?style;
    dbo:manufacturer ?manufacturer;
    dbp:class ?class;
    dbp:modelYears ?year;
    dbo:layout ?layout.

    FILTER(LANG(?name) = 'en')
    FILTER(LANG(?description) = 'en')
    FILTER(?year > "2000"^^xsd:integer)
}
LIMIT 1000